### ISSUE TITLE
How to use imput image?

### ISSUE THREAD

**Issue by seghier** [daltonks/BitmapToVector#2]
Hi
Where is the input image in this code?

```
// Create PotraceBitmap
var width = 100;
var height = 100;
using var potraceBitmap = PotraceBitmap.Create(width, height);

// Add black pixels
potraceBitmap.SetBlackUnsafe(0, 0);
potraceBitmap.SetBlackUnsafe(0, 1);

// Create options
var param = new PotraceParam();

// Trace using Potrace
var traceResult = Potrace.Trace(param, potraceBitmap);
```

**Comment by daltonks** [comment]
Potrace images are only black and white. If you want to create one from a specific image, you could iterate over the source image's pixels and `SetBlackUnsafe` wherever you want the Potrace image pixel to be black.
This library doesn't have features to determine which pixels "should" be black, so that part is up to you.

**Comment by daltonks** [comment]
Actually, that's not entirely accurate: if you're using the skiasharp version, `PotraceSkiaSharp.Trace` will treat all pixels with a red value less than 128 as "black".
